# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_chattingroom_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattingroom',
            name='room_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
