# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0007_auto_20170605_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattingroom',
            name='member',
            field=models.ManyToManyField(related_name='join', to=settings.AUTH_USER_MODEL),
        ),
    ]
