# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0008_auto_20170605_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usermember', to=settings.AUTH_USER_MODEL),
        ),
    ]
